.TH MYGREP 3 "2026-09-25" "libmyutils 1.0" "Library Functions Manual"
.SH NAME
mygrep \- search lines matching pattern in file
.SH SYNOPSIS
.B #include "myfilefunctions.h"
.sp
.BI "int mygrep(FILE *" fp ", const char *" search_str ", char ***" matches ");"
.SH DESCRIPTION
The
.BR mygrep ()
function searches for lines containing
.I search_str
and fills the
.I matches
array.
.SH AUTHOR
Ahmad Pervaiz <bsdsf24m013@pucit.edu.com>