.TH MYSTRNCPY 3 "2026-09-25" "libmyutils 1.0" "Library Functions Manual"
.SH NAME
mystrncpy \- copy a fixed length of characters from a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int mystrncpy(char *" dest ", const char *" src ", int " n ");"
.SH DESCRIPTION
The
.BR mystrncpy ()
function copies at most
.I n
bytes from string
.I src
to
.I dest
.
.SH AUTHOR
Ahmad Pervaiz <bsdsf24m013@pucit.edu.com>